CREATE VIEW PRODUCT_BY_PROVIDER AS
SELECT PROD.PRD_NAME, PROD.PRD_DESCRIPTION, PROV.PRO_SOCIAL_REASON
FROM FORNECEDOR_PRODUCT PROD
INNER JOIN FORNECEDOR_PROVIDER PROV ON PROD.PRD_PROVIDER_id=PROV.PROD_ID;